modLoader="javafml"
loaderVersion="[1.21,)"
license="MIT"

[[mods]]
modId="forgeauth"
version="1.0"
displayName="Auth"
description="Server authentification."
logoFile="logo.png"
authors="Stefan Bogdanovic"
credits="I needed this for AFKing."
displayURL="https://github.com/stefanbogdanov2c/minecraft-forge-auth"
issueTrackerURL="https://github.com/stefanbogdanov2c/minecraft-forge-auth/issues"

# Optional dependencies section
# [dependencies.auth]
# modId="forge"
# mandatory=true
# versionRange="[1.21,)"
# ordering="NONE"
# side="BOTH"
